# Data Validation Pipeline Template
# Data quality checking and validation

pipeline:
  - name: read_file
    id: reader
    config:
      path: "input/{{input_file}}"
    retry_attempts: 3

  - name: parse_json
    id: parser
    continue_on_error: false

  - name: json
    id: validator
    config:
      schema: |
        {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id", "name"],
            "properties": {
              "id": {"type": "number"},
              "name": {"type": "string"}
            }
          }
        }
    continue_on_error: false

  - name: write_file
    id: writer
    config:
      path: "output/validated_{{output_file}}"
      create_directories: true

# Pipeline metadata
metadata:
  name: "{{pipeline_name}}"
  description: "{{pipeline_description}}"
  version: "1.0.0"
  author: "{{pipeline_author}}"
  tags: ["validation", "quality", "schema"]
