# Test Pipeline with Environment Variables
# This pipeline demonstrates environment variable substitution

pipeline:
  - name: read_file
    id: reader
    config:
      path: "input.json"

  - name: parse_json
    id: parser

  - name: format_csv
    id: formatter
    config:
      headers: true
      delimiter: "${CSV_DELIMITER:-,}"

  - name: write_file
    id: writer
    config:
      path: "output/enhanced_data.csv"

metadata:
  name: "Enhanced Pipeline Test"
  description: "Tests environment variable substitution and step references"
  version: "2.0.0"
  author: "Oxide Flow"
