# Default JSON to CSV Pipeline
# This pipeline reads a JSON file, parses it, and converts it to CSV format

pipeline:
  - name: read_file
    id: reader
    config:
      path: "input.json"

  - name: parse_json
    id: parser

  - name: format_csv
    id: formatter
    config:
      headers: true
      delimiter: ","

  - name: write_file
    id: writer
    config:
      path: "output/data.csv"

# Pipeline metadata
metadata:
  name: "JSON to CSV Converter"
  description: "Converts JSON data to CSV format"
  version: "1.0.0"
  author: "Oxide Flow"
