# Batch Processing Pipeline Template
# Robust batch processing with comprehensive error handling

pipeline:
  - name: read_file
    id: reader
    config:
      path: "input/batch/data.json"
    retry_attempts: 5
    timeout_seconds: 60
    continue_on_error: false

  - name: parse_json
    id: parser
    retry_attempts: 3
    continue_on_error: false

  - name: flatten
    id: transformer
    config:
      separator: "_"
      max_depth: 3
    retry_attempts: 2
    continue_on_error: true

  - name: format_csv
    id: formatter
    config:
      headers: true
      delimiter: ","
      quote_all: true
    continue_on_error: true

  - name: write_file
    id: writer
    config:
      path: "output/batch/output.csv"
      create_directories: true
      backup: true
    retry_attempts: 3
    timeout_seconds: 30

  - name: write_file
    id: backup_writer
    config:
      path: "backup/template_batch_backup.csv"
      create_directories: true
    continue_on_error: true

# Pipeline metadata
metadata:
  name: "Template Batch"
  description: "Batch template test pipeline"
  version: "1.0.0"
  author: "Template Testing"
  tags: ["batch", "robust", "error-handling"]
