name: "Test Text Batch Processing"
description: "Test pipeline for demonstrating text batch Oxi functionality"
version: "1.0.0"

pipeline:
  - name: read_stdin
  - name: batch
    config:
      batch_size: 2
      strategy: "Size"
  - name: write_stdout
